package org.common.type;

public enum EventType {
  ORDER_CREATED,
  ORDER_CANCELLED,
  ORDER_SUCCEEDED,

  INVENTORY_CREATED,
  INVENTORY_CANCELLED,
  INVENTORY_SUCCEEDED,

  PAYMENT_CREATED,
  PAYMENT_CANCELLED,
  PAYMENT_SUCCEEDED,
  ;
}
